stages:
  - build

build-back:
  image: 
    name: registry.gitlab.inria.fr/diverse/insa/docker-image/insa-maven:3.9.8-eclipse-temurin-21
#    pull_policy: if-not-present
  stage: build
  script:
    - cd backend
    - mvn clean package spring-boot:repackage
  artifacts:
    paths:
      - backend/target/site/jacoco/jacoco.xml
      - backend/target/backend-0.0.1.jar
    expire_in: 1 hour

build-front:
  image: 
    name: registry.gitlab.inria.fr/diverse/insa/docker-image/insa-node:22.18.0
#    pull_policy: if-not-present
  stage: build
  cache:
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm install
    - npm run ng build -- --configuration production
  artifacts:
    paths:
      - frontend/dist/frontend/
    expire_in: 1 hour

